/**
 * @lingolive/design-tokens — the single source of colour, spacing, type and
 * motion values for every LingoLive surface.
 *
 * Hard rule enforced in review: no component, anywhere, hard-codes a colour or
 * a radius. Web reads these through CSS custom properties generated by
 * `cssVariables()`; React Native reads the objects directly.
 */

// ---------------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------------

export const palette = {
  primary: '#2F6BFF',
  primaryDark: '#1F4FD0',
  primarySoft: '#EAF0FF',

  live: '#14A88B',
  liveSoft: '#E5F8F3',

  ink: '#0D1726',
  inkSecondary: '#5D6979',
  inkMuted: '#8591A1',

  backgroundLight: '#F5F7FB',
  surfaceLight: '#FFFFFF',
  borderLight: '#DDE3EC',

  danger: '#D92D20',
  dangerSoft: '#FEECEB',
  warning: '#D97706',

  backgroundDark: '#07111F',
  surfaceDark: '#101C2E',
  surfaceDarkSecondary: '#162338',
  borderDark: '#283750',
  inkDark: '#F7F9FC',
  inkDarkSecondary: '#B8C2D1',

  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
} as const;

export type ThemeName = 'light' | 'dark';

export interface ThemeColors {
  background: string;
  surface: string;
  surfaceElevated: string;
  border: string;
  borderStrong: string;

  text: string;
  textSecondary: string;
  textMuted: string;
  textOnPrimary: string;

  primary: string;
  primaryHover: string;
  primarySoft: string;
  primaryText: string;

  live: string;
  liveSoft: string;
  liveText: string;

  danger: string;
  dangerSoft: string;
  warning: string;

  /** Partial (non-final) transcript text — lower contrast, still AA-legible. */
  transcriptPartial: string;
  transcriptFinal: string;

  /** Focus ring for keyboard navigation (WCAG 2.2 §2.4.11/2.4.13). */
  focusRing: string;
  overlay: string;
}

export const lightTheme: ThemeColors = {
  background: palette.backgroundLight,
  surface: palette.surfaceLight,
  surfaceElevated: palette.surfaceLight,
  border: palette.borderLight,
  borderStrong: '#C3CCDA',

  text: palette.ink,
  textSecondary: palette.inkSecondary,
  textMuted: palette.inkMuted,
  textOnPrimary: palette.white,

  primary: palette.primary,
  primaryHover: palette.primaryDark,
  primarySoft: palette.primarySoft,
  primaryText: palette.primaryDark,

  live: palette.live,
  liveSoft: palette.liveSoft,
  liveText: '#0B7A64',

  danger: palette.danger,
  dangerSoft: palette.dangerSoft,
  warning: palette.warning,

  transcriptPartial: palette.inkSecondary,
  transcriptFinal: palette.ink,

  focusRing: palette.primary,
  overlay: 'rgba(13, 23, 38, 0.55)',
};

export const darkTheme: ThemeColors = {
  background: palette.backgroundDark,
  surface: palette.surfaceDark,
  surfaceElevated: palette.surfaceDarkSecondary,
  border: palette.borderDark,
  borderStrong: '#3A4C6B',

  text: palette.inkDark,
  textSecondary: palette.inkDarkSecondary,
  textMuted: '#8A97A9',
  textOnPrimary: palette.white,

  primary: '#5B8CFF',
  primaryHover: '#7BA3FF',
  primarySoft: '#16294A',
  primaryText: '#A9C3FF',

  live: '#2ECFAE',
  liveSoft: '#0E2E29',
  liveText: '#6FE3C9',

  danger: '#F97066',
  dangerSoft: '#3A1512',
  warning: '#F5A623',

  transcriptPartial: palette.inkDarkSecondary,
  transcriptFinal: palette.inkDark,

  focusRing: '#8AB0FF',
  overlay: 'rgba(3, 8, 15, 0.7)',
};

export const themes: Record<ThemeName, ThemeColors> = {
  light: lightTheme,
  dark: darkTheme,
};

// ---------------------------------------------------------------------------
// Shape
// ---------------------------------------------------------------------------

export const radius = {
  /** Small controls: chips, inline pills. */
  sm: 12,
  /** Buttons. */
  md: 16,
  /** Standard cards. */
  lg: 18,
  /** Large hero cards (Listen / Discuss / Join). */
  xl: 24,
  /** Fully rounded. */
  full: 999,
} as const;

export const spacing = {
  none: 0,
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  base: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 48,
  huge: 64,
} as const;

/**
 * Minimum interactive size. WCAG 2.2 AA (§2.5.8) requires 24×24 CSS px; Apple
 * HIG and Material both ask for 44–48. LingoLive standardises on 48 because it
 * is used one-handed, often in motion, sometimes in the dark.
 */
export const MIN_TOUCH_TARGET = 48;

/** Push-to-talk buttons are much larger than a normal control by design. */
export const SPEAK_BUTTON_SIZE = 88;

// ---------------------------------------------------------------------------
// Typography
// ---------------------------------------------------------------------------

export const fontSize = {
  display: 40,
  h1: 32,
  h2: 26,
  title: 20,
  body: 17,
  bodySmall: 15,
  caption: 13,
  /** Live transcript scales between these bounds via pinch / settings. */
  transcriptMin: 20,
  transcriptDefault: 24,
  transcriptMax: 30,
} as const;

export const fontWeight = {
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
} as const;

/**
 * Letter-spacing, which is the difference between type that was set and type
 * that was merely rendered.
 *
 * Optical sizing: at display sizes the default spacing looks loose and the
 * words fail to read as one shape, so it tightens as size grows. Small text
 * goes the other way — caption and label sizes need a little air to stay
 * legible, especially reversed out or at a glance.
 */
export const tracking = {
  display: '-0.022em',
  h1: '-0.019em',
  h2: '-0.016em',
  title: '-0.012em',
  body: '-0.006em',
  caption: '0',
  label: '0.006em',
} as const;

export const lineHeight = {
  tight: 1.2,
  snug: 1.35,
  normal: 1.5,
  relaxed: 1.65,
} as const;

/**
 * Web font stack. `Inter` is loaded with `font-display: swap` and a system
 * fallback that has near-identical metrics, so there is no layout shift (CLS).
 * Mobile deliberately uses the platform font (San Francisco / Roboto) so that
 * Dynamic Type and the user's accessibility settings are respected for free.
 */
export const fontFamily = {
  web: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
  webMono: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
  ios: 'System',
  android: 'sans-serif',
} as const;

/** Clamp for the user-controlled transcript scale (pinch or settings slider). */
export const TRANSCRIPT_SCALE_MIN = 0.75;
export const TRANSCRIPT_SCALE_MAX = 2.5;
export const TRANSCRIPT_SCALE_DEFAULT = 1;

export function clampTranscriptScale(value: number): number {
  if (!Number.isFinite(value)) return TRANSCRIPT_SCALE_DEFAULT;
  return Math.min(TRANSCRIPT_SCALE_MAX, Math.max(TRANSCRIPT_SCALE_MIN, value));
}

export function transcriptFontSize(scale: number): number {
  return Math.round(fontSize.transcriptDefault * clampTranscriptScale(scale));
}

// ---------------------------------------------------------------------------
// Motion — short and functional only. Nothing decorative.
// ---------------------------------------------------------------------------

export const duration = {
  instant: 0,
  fast: 150,
  base: 180,
  slow: 220,
  /** The one exception: the Live pulse, which loops. */
  pulse: 1600,
} as const;

export const easing = {
  standard: 'cubic-bezier(0.2, 0, 0, 1)',
  decelerate: 'cubic-bezier(0, 0, 0, 1)',
  accelerate: 'cubic-bezier(0.3, 0, 1, 1)',
  /**
   * Slight overshoot, for something arriving rather than being placed.
   * Deliberately gentle: at a real spring's amplitude this reads as a wobble,
   * and a wobble on every button press is a tic.
   */
  spring: 'cubic-bezier(0.34, 1.4, 0.64, 1)',
} as const;

/** Every animation must go through this so Reduce Motion is never ignored. */
export function motionDuration(ms: number, reduceMotion: boolean): number {
  return reduceMotion ? 0 : ms;
}

// ---------------------------------------------------------------------------
// Elevation
// ---------------------------------------------------------------------------

/**
 * Depth, built from two shadows rather than one.
 *
 * A single blurred shadow reads as a drop shadow. Two — a tight contact shadow
 * that anchors the edge, plus a wide soft one for the ambient light — reads as
 * an object sitting on a surface. The tight one carries most of the definition
 * and the wide one almost none, which is why both are barely visible on their
 * own.
 */
export const shadow = {
  none: { web: 'none', elevation: 0 },
  card: {
    web: '0 1px 2px rgba(13,23,38,0.05), 0 8px 24px -8px rgba(13,23,38,0.10)',
    elevation: 2,
  },
  raised: {
    web: '0 2px 6px rgba(13,23,38,0.07), 0 20px 48px -16px rgba(13,23,38,0.16)',
    elevation: 6,
  },
  /** A control under the finger: pulled in, not pushed out. */
  pressed: {
    web: 'inset 0 1px 3px rgba(13,23,38,0.14)',
    elevation: 0,
  },
  /** Whoever is talking, visible across a table and upside down. */
  speaking: {
    web: '0 0 0 4px rgba(20,168,139,0.16), 0 8px 28px -6px rgba(20,168,139,0.35)',
    elevation: 8,
  },
} as const;

/**
 * Translucent materials.
 *
 * A bar that lets the content blur through it belongs to the page instead of
 * covering it, and it tells you there is more above or below without a line or
 * a shadow doing the shouting. Falls back to the opaque surface colour wherever
 * `backdrop-filter` is unavailable — the layout never depends on it.
 */
export const material = {
  /** Sticky headers and bottom bars. */
  bar: {
    light: 'rgba(255,255,255,0.72)',
    dark: 'rgba(16,28,46,0.72)',
    blur: '20px',
  },
  /** Sheets and dialogs, which sit further from the page. */
  sheet: {
    light: 'rgba(255,255,255,0.86)',
    dark: 'rgba(16,28,46,0.86)',
    blur: '30px',
  },
} as const;

export const breakpoints = {
  /** Phone. */
  sm: 480,
  /** Large phone / small tablet. */
  md: 768,
  /** Tablet landscape. */
  lg: 1024,
  /** Desktop. */
  xl: 1280,
} as const;

export const zIndex = {
  base: 0,
  sticky: 10,
  overlay: 100,
  modal: 200,
  toast: 300,
  liveIndicator: 400,
} as const;

// ---------------------------------------------------------------------------
// Web bridge
// ---------------------------------------------------------------------------

function toKebab(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** Emits the `--ll-*` custom properties consumed by the web stylesheet. */
export function cssVariables(theme: ThemeName): Record<string, string> {
  const colors = themes[theme];
  const vars: Record<string, string> = {};
  for (const [key, value] of Object.entries(colors)) {
    vars[`--ll-color-${toKebab(key)}`] = value;
  }
  for (const [key, value] of Object.entries(radius)) {
    vars[`--ll-radius-${toKebab(key)}`] = `${value}px`;
  }
  for (const [key, value] of Object.entries(spacing)) {
    vars[`--ll-space-${toKebab(key)}`] = `${value}px`;
  }
  for (const [key, value] of Object.entries(fontSize)) {
    vars[`--ll-font-size-${toKebab(key)}`] = `${value}px`;
  }
  for (const [key, value] of Object.entries(duration)) {
    vars[`--ll-duration-${toKebab(key)}`] = `${value}ms`;
  }
  vars['--ll-font-family'] = fontFamily.web;
  vars['--ll-font-family-mono'] = fontFamily.webMono;
  for (const [key, value] of Object.entries(tracking)) {
    vars[`--ll-tracking-${toKebab(key)}`] = value;
  }
  vars['--ll-easing-standard'] = easing.standard;
  vars['--ll-easing-spring'] = easing.spring;
  vars['--ll-easing-decelerate'] = easing.decelerate;
  vars['--ll-shadow-card'] = shadow.card.web;
  vars['--ll-shadow-raised'] = shadow.raised.web;
  vars['--ll-shadow-pressed'] = shadow.pressed.web;
  vars['--ll-shadow-speaking'] = shadow.speaking.web;
  vars['--ll-material-bar'] = material.bar[theme];
  vars['--ll-material-bar-blur'] = material.bar.blur;
  vars['--ll-material-sheet'] = material.sheet[theme];
  vars['--ll-material-sheet-blur'] = material.sheet.blur;
  vars['--ll-min-touch-target'] = `${MIN_TOUCH_TARGET}px`;
  return vars;
}

export function cssVariableBlock(theme: ThemeName, selector: string): string {
  const entries = Object.entries(cssVariables(theme))
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n');
  return `${selector} {\n${entries}\n}`;
}

// ---------------------------------------------------------------------------
// Contrast — asserted by unit tests so a palette edit cannot silently regress
// accessibility.
// ---------------------------------------------------------------------------

function channelLuminance(channel: number): number {
  const c = channel / 255;
  return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

export function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const normalized = hex.replace('#', '').trim();
  if (normalized.length !== 6) return null;
  const r = Number.parseInt(normalized.slice(0, 2), 16);
  const g = Number.parseInt(normalized.slice(2, 4), 16);
  const b = Number.parseInt(normalized.slice(4, 6), 16);
  if ([r, g, b].some((v) => Number.isNaN(v))) return null;
  return { r, g, b };
}

export function relativeLuminance(hex: string): number {
  const rgb = hexToRgb(hex);
  if (!rgb) return 0;
  return (
    0.2126 * channelLuminance(rgb.r) +
    0.7152 * channelLuminance(rgb.g) +
    0.0722 * channelLuminance(rgb.b)
  );
}

/** WCAG 2.x contrast ratio, 1–21. */
export function contrastRatio(foreground: string, background: string): number {
  const l1 = relativeLuminance(foreground);
  const l2 = relativeLuminance(background);
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return (lighter + 0.05) / (darker + 0.05);
}

export function meetsContrastAA(
  foreground: string,
  background: string,
  size: 'normal' | 'large' = 'normal',
): boolean {
  return contrastRatio(foreground, background) >= (size === 'large' ? 3 : 4.5);
}
