import { buildPage } from './build-page';
import type { Guide, MarketingPage } from './types';
import type { CopyRow } from './build-page';
import type { UiLocale } from '@lingolive/contracts';

/**
 * The editorial space.
 *
 * Two guides, each answering a question people genuinely ask before a real
 * event. Deliberately few: a handful of pages worth reading beats fifty thin
 * ones, and search engines agree.
 */

function guide(slug: string, publishedAt: string, rows: Record<UiLocale, CopyRow>): Guide {
  const page = buildPage({
    path: `guides/${slug}`,
    kind: 'informational',
    ctaPath: 'listen',
    rows,
  });
  return { slug, publishedAt, updatedAt: publishedAt, copy: page.copy };
}

const runningMultilingualMeeting = guide('running-a-multilingual-meeting', '2026-07-31', {
  en: [
    'How to run a multilingual meeting | LingoLive guides',
    'Practical steps for a meeting where not everyone shares a language: seating, microphone placement, turn-taking and what to do about jargon.',
    'How to run a multilingual meeting',
    'Live captions help, but the room matters more than the software. These are the things that make the difference between a transcript people can follow and one they give up on.',
    'Put the microphone where the quiet person is',
    'Transcription quality is dominated by distance and by who is furthest from the device. Place the phone nearer the people who speak softly, not in the geometric centre of the table, and keep it off a surface that resonates.',
    'One voice at a time, and say the names',
    'Overlapping speech is the single largest cause of garbled transcripts. Agree at the start that people finish sentences before others begin. Say names and numbers a little more deliberately than usual — they are what people scan the transcript for afterwards.',
    'Start listening',
  ],
  fr: [
    'Comment mener une réunion multilingue | Guides LingoLive',
    'Des étapes concrètes pour une réunion où tout le monde ne partage pas la même langue : placement, micro, tours de parole, et que faire du jargon.',
    'Comment mener une réunion multilingue',
    "Les sous-titres aident, mais la salle compte plus que le logiciel. Voici ce qui fait la différence entre un transcript qu'on suit et un transcript qu'on abandonne.",
    'Placez le micro du côté de la personne la plus discrète',
    "La qualité de transcription dépend surtout de la distance et de la personne la plus éloignée de l'appareil. Posez le téléphone près de ceux qui parlent doucement, pas au centre géométrique de la table, et évitez une surface qui résonne.",
    'Une voix à la fois, et dites les noms',
    "Les prises de parole simultanées sont la première cause de transcripts illisibles. Convenez au départ que chacun finit sa phrase avant qu'un autre commence. Prononcez les noms et les nombres un peu plus nettement que d'habitude : c'est ce que les gens cherchent ensuite dans le texte.",
    'Commencer à écouter',
  ],
  ar: [
    'كيف تدير اجتماعًا متعدد اللغات | أدلة LingoLive',
    'خطوات عملية لاجتماع لا يتشارك فيه الجميع لغة واحدة: الجلوس، وموضع الميكروفون، وتناوب الكلام، وماذا تفعل بالمصطلحات.',
    'كيف تدير اجتماعًا متعدد اللغات',
    'النصوص المباشرة تساعد، لكن القاعة أهم من البرنامج. هذه هي الأمور التي تفرق بين نص يمكن متابعته ونص يتخلى عنه الناس.',
    'ضع الميكروفون تجاه أهدأ الأصوات',
    'تتحدد جودة التفريغ أساسًا بالمسافة وبمن هو أبعد عن الجهاز. ضع الهاتف قرب من يتحدثون بصوت منخفض، لا في مركز الطاولة الهندسي، وتجنّب سطحًا يرنّ.',
    'صوت واحد في كل مرة، وانطق الأسماء',
    'تداخل الكلام هو السبب الأول للنصوص المشوّشة. اتفقوا في البداية على إنهاء الجمل قبل أن يبدأ غيركم. وانطق الأسماء والأرقام بوضوح أكبر قليلًا من المعتاد، فهي ما يبحث عنه الناس في النص لاحقًا.',
    'ابدأ الاستماع',
  ],
  es: [
    'Cómo dirigir una reunión multilingüe | Guías LingoLive',
    'Pasos prácticos para una reunión en la que no todos comparten idioma: colocación, micrófono, turnos de palabra y qué hacer con la jerga.',
    'Cómo dirigir una reunión multilingüe',
    'Los subtítulos ayudan, pero la sala importa más que el software. Esto es lo que marca la diferencia entre una transcripción que se puede seguir y otra que la gente abandona.',
    'Pon el micrófono del lado de quien habla más bajo',
    'La calidad de la transcripción depende sobre todo de la distancia y de quién está más lejos del dispositivo. Coloca el móvil cerca de quienes hablan flojo, no en el centro geométrico de la mesa, y evita superficies que resuenen.',
    'Una voz cada vez, y di los nombres',
    'Hablar a la vez es la mayor causa de transcripciones ininteligibles. Acordad al principio que cada persona termina su frase antes de que empiece otra. Pronuncia nombres y cifras algo más marcadamente de lo habitual: es lo que la gente busca después en el texto.',
    'Empezar a escuchar',
  ],
  'pt-BR': [
    'Como conduzir uma reunião multilíngue | Guias LingoLive',
    'Passos práticos para uma reunião em que nem todos falam o mesmo idioma: disposição, microfone, turnos de fala e o que fazer com o jargão.',
    'Como conduzir uma reunião multilíngue',
    'As legendas ajudam, mas a sala importa mais que o software. Estas são as coisas que separam uma transcrição que dá para acompanhar de uma que as pessoas abandonam.',
    'Ponha o microfone do lado de quem fala mais baixo',
    'A qualidade da transcrição depende sobretudo da distância e de quem está mais longe do aparelho. Coloque o celular perto de quem fala baixo, não no centro geométrico da mesa, e evite superfícies que ressoam.',
    'Uma voz por vez, e diga os nomes',
    'Falas sobrepostas são a maior causa de transcrições embaralhadas. Combinem no início que cada pessoa termina a frase antes de outra começar. Pronuncie nomes e números com um pouco mais de clareza que o normal — é o que as pessoas procuram no texto depois.',
    'Começar a ouvir',
  ],
  it: [
    'Come condurre una riunione multilingue | Guide LingoLive',
    'Passi pratici per una riunione in cui non tutti condividono la lingua: disposizione, microfono, turni di parola e cosa fare con il gergo.',
    'Come condurre una riunione multilingue',
    'I sottotitoli aiutano, ma la sala conta più del software. Ecco cosa fa la differenza tra una trascrizione che si riesce a seguire e una che si abbandona.',
    'Metti il microfono dal lato di chi parla piano',
    'La qualità della trascrizione dipende soprattutto dalla distanza e da chi è più lontano dal dispositivo. Appoggia il telefono vicino a chi parla sottovoce, non al centro geometrico del tavolo, ed evita superfici che risuonano.',
    'Una voce alla volta, e pronuncia i nomi',
    'Le sovrapposizioni sono la prima causa di trascrizioni confuse. Concordate all’inizio che ognuno finisce la frase prima che un altro cominci. Pronuncia nomi e numeri un po’ più nitidamente del solito: è ciò che le persone cercano nel testo dopo.',
    'Inizia ad ascoltare',
  ],
  de: [
    'Wie man ein mehrsprachiges Meeting führt | LingoLive-Guides',
    'Praktische Schritte für ein Meeting, in dem nicht alle dieselbe Sprache sprechen: Sitzordnung, Mikrofon, Redebeiträge und der Umgang mit Fachjargon.',
    'Wie man ein mehrsprachiges Meeting führt',
    'Live-Untertitel helfen, aber der Raum zählt mehr als die Software. Das hier macht den Unterschied zwischen einem Transkript, dem man folgen kann, und einem, das man aufgibt.',
    'Leg das Mikrofon zur leisesten Person hin',
    'Die Transkriptionsqualität hängt vor allem von der Distanz ab und von der Person, die am weitesten vom Gerät entfernt ist. Leg das Handy näher zu denen, die leise sprechen — nicht in die geometrische Tischmitte — und meide resonierende Oberflächen.',
    'Eine Stimme zur Zeit, und Namen aussprechen',
    'Überlappendes Sprechen ist die größte Ursache unbrauchbarer Transkripte. Vereinbart am Anfang, dass Sätze zu Ende gesprochen werden. Sprich Namen und Zahlen etwas deutlicher als üblich — genau danach sucht man später im Text.',
    'Jetzt zuhören',
  ],
});

const captioningAnEvent = guide('captioning-a-conference-talk', '2026-07-31', {
  en: [
    'How to caption a conference talk | LingoLive guides',
    'Getting a room of attendees reading along in their own languages: the code, the languages to enable, and what to do when the venue Wi-Fi struggles.',
    'How to caption a conference talk',
    'Attendees read on their own phones, which means your job is mostly about getting the code in front of them and choosing the right languages before you start.',
    'Show the code where people are already looking',
    'Put the six-digit code and the QR code on the holding slide before the session, not on a slide you advance past. People arrive at different times, and someone who sits down five minutes in still needs it.',
    'Enable the languages people asked for, not every language',
    'Each active language is one translation per sentence. Enabling twelve languages when three are being read costs nine translations of nothing. Registration data is usually a better guide than guessing.',
    'Join a session',
  ],
  fr: [
    'Comment sous-titrer une intervention en conférence | Guides LingoLive',
    'Faire lire toute une salle dans sa langue : le code, les langues à activer, et que faire quand le Wi-Fi du lieu peine.',
    'Comment sous-titrer une intervention en conférence',
    'Les participants lisent sur leur propre téléphone : votre travail consiste surtout à mettre le code sous leurs yeux et à choisir les bonnes langues avant de commencer.',
    'Affichez le code là où les gens regardent déjà',
    "Mettez le code à six chiffres et le QR code sur la diapositive d'attente avant la session, pas sur une diapositive que vous ferez défiler. Les gens arrivent à des moments différents, et quelqu'un qui s'assoit cinq minutes après en a toujours besoin.",
    'Activez les langues demandées, pas toutes les langues',
    "Chaque langue active correspond à une traduction par phrase. Activer douze langues quand trois sont lues, c'est payer neuf traductions pour personne. Les données d'inscription valent mieux qu'une intuition.",
    'Rejoindre une session',
  ],
  ar: [
    'كيف تضيف نصوصًا لكلمة في مؤتمر | أدلة LingoLive',
    'كيف تجعل قاعة كاملة تقرأ بلغاتها: الرمز، واللغات التي تفعّلها، وماذا تفعل حين تتعثّر شبكة المكان.',
    'كيف تضيف نصوصًا لكلمة في مؤتمر',
    'يقرأ الحضور على هواتفهم، ما يعني أن مهمتك تنحصر غالبًا في إيصال الرمز إليهم واختيار اللغات الصحيحة قبل البدء.',
    'اعرض الرمز حيث ينظر الناس أصلًا',
    'ضع الرمز المكوّن من ستة أرقام ورمز QR على شريحة الانتظار قبل الجلسة، لا على شريحة ستتجاوزها. يصل الناس في أوقات مختلفة، ومن يجلس بعد خمس دقائق لا يزال يحتاجه.',
    'فعّل اللغات المطلوبة، لا كل اللغات',
    'كل لغة مفعّلة تعني ترجمة إضافية لكل جملة. تفعيل اثنتي عشرة لغة بينما تُقرأ ثلاث يعني دفع تسع ترجمات بلا قارئ. بيانات التسجيل أفضل دليل من التخمين.',
    'الانضمام إلى جلسة',
  ],
  es: [
    'Cómo subtitular una ponencia de congreso | Guías LingoLive',
    'Conseguir que toda una sala lea en su idioma: el código, los idiomas que activar y qué hacer cuando el wifi de la sede flaquea.',
    'Cómo subtitular una ponencia de congreso',
    'El público lee en su propio móvil, así que tu trabajo consiste sobre todo en poner el código delante de ellos y elegir bien los idiomas antes de empezar.',
    'Muestra el código donde la gente ya está mirando',
    'Pon el código de seis dígitos y el QR en la diapositiva de espera antes de la sesión, no en una que vayas a pasar. La gente llega en momentos distintos y quien se sienta cinco minutos después sigue necesitándolo.',
    'Activa los idiomas que han pedido, no todos',
    'Cada idioma activo es una traducción por frase. Activar doce idiomas cuando se leen tres son nueve traducciones para nadie. Los datos de inscripción suelen guiar mejor que la intuición.',
    'Unirse a una sesión',
  ],
  'pt-BR': [
    'Como legendar uma palestra de congresso | Guias LingoLive',
    'Fazer uma sala inteira ler no próprio idioma: o código, os idiomas a ativar e o que fazer quando o wi-fi do local vacila.',
    'Como legendar uma palestra de congresso',
    'O público lê no próprio celular, então seu trabalho é principalmente colocar o código diante das pessoas e escolher os idiomas certos antes de começar.',
    'Mostre o código onde as pessoas já estão olhando',
    'Coloque o código de seis dígitos e o QR no slide de espera antes da sessão, não em um slide que você vai passar. As pessoas chegam em momentos diferentes, e quem senta cinco minutos depois ainda precisa dele.',
    'Ative os idiomas que pediram, não todos',
    'Cada idioma ativo é uma tradução por frase. Ativar doze idiomas quando três estão sendo lidos são nove traduções para ninguém. Os dados de inscrição costumam orientar melhor que o palpite.',
    'Entrar em uma sessão',
  ],
  it: [
    'Come sottotitolare un intervento in conferenza | Guide LingoLive',
    'Far leggere un’intera sala nella propria lingua: il codice, le lingue da attivare e cosa fare quando il Wi-Fi della sede arranca.',
    'Come sottotitolare un intervento in conferenza',
    'I partecipanti leggono sul proprio telefono, quindi il tuo lavoro consiste soprattutto nel mettere il codice davanti a loro e scegliere le lingue giuste prima di iniziare.',
    'Mostra il codice dove le persone già guardano',
    'Metti il codice a sei cifre e il QR sulla slide di attesa prima della sessione, non su una che scorrerai via. Le persone arrivano in momenti diversi, e chi si siede cinque minuti dopo ne ha ancora bisogno.',
    'Attiva le lingue richieste, non tutte',
    'Ogni lingua attiva è una traduzione per frase. Attivarne dodici quando se ne leggono tre significa pagare nove traduzioni per nessuno. I dati di iscrizione sono una guida migliore dell’intuito.',
    'Entra in una sessione',
  ],
  de: [
    'Wie man einen Konferenzvortrag untertitelt | LingoLive-Guides',
    'Einen ganzen Saal in seinen Sprachen mitlesen lassen: der Code, die zu aktivierenden Sprachen und was tun, wenn das WLAN der Location schwächelt.',
    'Wie man einen Konferenzvortrag untertitelt',
    'Teilnehmende lesen auf dem eigenen Handy — deine Aufgabe besteht also vor allem darin, ihnen den Code vor Augen zu bringen und vorher die richtigen Sprachen zu wählen.',
    'Zeig den Code dort, wo alle ohnehin hinschauen',
    'Setz den sechsstelligen Code und den QR-Code auf die Wartefolie vor der Session, nicht auf eine Folie, über die du hinwegblätterst. Menschen kommen zu unterschiedlichen Zeiten, und wer sich nach fünf Minuten setzt, braucht ihn immer noch.',
    'Aktiviere die gewünschten Sprachen, nicht alle',
    'Jede aktive Sprache ist eine Übersetzung pro Satz. Zwölf Sprachen zu aktivieren, während drei gelesen werden, sind neun Übersetzungen für niemanden. Anmeldedaten sind meist ein besserer Anhaltspunkt als Raten.',
    'Einer Sitzung beitreten',
  ],
});

export const GUIDES: readonly Guide[] = [runningMultilingualMeeting, captioningAnEvent];

/** The `/guides` index. */
export const GUIDES_INDEX: MarketingPage = buildPage({
  path: 'guides',
  kind: 'guide-index',
  ctaPath: 'listen',
  rows: {
    en: [
      'Guides | LingoLive',
      'Short, practical guides on running multilingual meetings and captioning events — written for the room, not for the software.',
      'Guides',
      'A small number of guides that answer questions people actually ask before a real event.',
      'Written from real constraints',
      'Every guide starts from something that goes wrong in practice — a noisy table, a venue network, a room where nobody agreed who speaks first — rather than from a feature list.',
      'Kept short',
      'There are two guides, not fifty. Each is meant to be read once, before the thing you are about to do.',
      'Read the guides',
    ],
    fr: [
      'Guides | LingoLive',
      'Des guides courts et concrets pour mener des réunions multilingues et sous-titrer des événements — écrits pour la salle, pas pour le logiciel.',
      'Guides',
      'Quelques guides qui répondent aux questions que les gens se posent vraiment avant un événement.',
      'Écrits à partir de contraintes réelles',
      "Chaque guide part de ce qui se passe mal en pratique — une table bruyante, le réseau d'un lieu, une salle où personne n'a décidé qui parle en premier — et non d'une liste de fonctionnalités.",
      'Volontairement courts',
      'Il y a deux guides, pas cinquante. Chacun se lit une fois, juste avant ce que vous vous apprêtez à faire.',
      'Lire les guides',
    ],
    ar: [
      'الأدلة | LingoLive',
      'أدلة قصيرة وعملية لإدارة اجتماعات متعددة اللغات وإضافة نصوص للفعاليات — مكتوبة للقاعة لا للبرنامج.',
      'الأدلة',
      'عدد قليل من الأدلة يجيب عن أسئلة يطرحها الناس فعلًا قبل أي فعالية حقيقية.',
      'مكتوبة من قيود واقعية',
      'ينطلق كل دليل مما يسوء عمليًا — طاولة صاخبة، شبكة المكان، قاعة لم يتفق فيها أحد على من يتحدث أولًا — لا من قائمة ميزات.',
      'قصيرة عن قصد',
      'هناك دليلان لا خمسون. كل واحد يُقرأ مرة واحدة قبل ما أنت مقبل عليه.',
      'اقرأ الأدلة',
    ],
    es: [
      'Guías | LingoLive',
      'Guías breves y prácticas para dirigir reuniones multilingües y subtitular eventos: escritas para la sala, no para el software.',
      'Guías',
      'Unas pocas guías que responden a las preguntas que la gente se hace de verdad antes de un evento.',
      'Escritas desde restricciones reales',
      'Cada guía parte de algo que sale mal en la práctica —una mesa ruidosa, la red de una sede, una sala donde nadie acordó quién habla primero— y no de una lista de funciones.',
      'Deliberadamente breves',
      'Hay dos guías, no cincuenta. Cada una está pensada para leerse una vez, justo antes de lo que vas a hacer.',
      'Leer las guías',
    ],
    'pt-BR': [
      'Guias | LingoLive',
      'Guias curtos e práticos para conduzir reuniões multilíngues e legendar eventos — escritos para a sala, não para o software.',
      'Guias',
      'Poucos guias que respondem às perguntas que as pessoas realmente fazem antes de um evento.',
      'Escritos a partir de restrições reais',
      'Cada guia parte de algo que dá errado na prática — uma mesa barulhenta, a rede do local, uma sala onde ninguém combinou quem fala primeiro — e não de uma lista de recursos.',
      'Curtos de propósito',
      'São dois guias, não cinquenta. Cada um foi feito para ser lido uma vez, pouco antes do que você vai fazer.',
      'Ler os guias',
    ],
    it: [
      'Guide | LingoLive',
      'Guide brevi e pratiche per condurre riunioni multilingue e sottotitolare eventi: scritte per la sala, non per il software.',
      'Guide',
      'Poche guide che rispondono alle domande che le persone si pongono davvero prima di un evento.',
      'Scritte da vincoli reali',
      'Ogni guida parte da qualcosa che va storto nella pratica — un tavolo rumoroso, la rete di una sede, una sala dove nessuno ha deciso chi parla per primo — non da un elenco di funzionalità.',
      'Volutamente brevi',
      'Ci sono due guide, non cinquanta. Ognuna è pensata per essere letta una volta, poco prima di ciò che stai per fare.',
      'Leggi le guide',
    ],
    de: [
      'Guides | LingoLive',
      'Kurze, praktische Guides für mehrsprachige Meetings und untertitelte Veranstaltungen — für den Raum geschrieben, nicht für die Software.',
      'Guides',
      'Wenige Guides, die Fragen beantworten, die vor einer echten Veranstaltung tatsächlich gestellt werden.',
      'Aus echten Zwängen geschrieben',
      'Jeder Guide beginnt bei etwas, das in der Praxis schiefgeht — ein lauter Tisch, das Netz einer Location, ein Raum, in dem niemand geklärt hat, wer zuerst spricht — statt bei einer Feature-Liste.',
      'Bewusst kurz',
      'Es gibt zwei Guides, nicht fünfzig. Jeder ist zum einmaligen Lesen gedacht, kurz vor dem, was du vorhast.',
      'Guides lesen',
    ],
  },
});
