import { buildPage } from './build-page';
import type { MarketingPage } from './types';

/**
 * Situation pages.
 *
 * Each one describes a real situation the product is used in. They exist
 * because "live translation" means something different in a lecture hall than
 * it does in a taxi — not to multiply URLs. There are seven of them, each with
 * its own framing, not a template with a swapped noun.
 */

const conversationTranslator = buildPage({
  path: 'conversation-translator',
  kind: 'use-case',
  ctaPath: 'discuss',
  rows: {
    en: [
      'Conversation translator for 2 to 4 people | LingoLive',
      'One phone on the table, up to four languages. Each person reads in their own language from their own side, and speaks with their own button.',
      'A conversation translator you put on the table',
      'Set the phone down between you. Each person gets a panel turned toward them — their language, their microphone, their side of the table. Nobody has to pass a device back and forth.',
      'Rotated for the person reading it',
      'Each panel can be turned in 90° steps so the text reads upright from where that person is sitting. Rotating a panel never rotates the screen, and never flips right-to-left languages the wrong way round.',
      'Push to talk, or hold',
      'Tap once to start a turn and let it end on its own, or hold the button while you speak. The other microphones dim while someone is talking, so two people cannot talk over the transcription.',
      'Open Discuss',
    ],
    fr: [
      'Traducteur de conversation pour 2 à 4 personnes | LingoLive',
      "Un téléphone sur la table, jusqu'à quatre langues. Chacun lit dans sa langue depuis son côté, et parle avec son propre bouton.",
      'Un traducteur de conversation que vous posez sur la table',
      "Posez le téléphone entre vous. Chacun a sa case orientée vers lui : sa langue, son micro, son côté de la table. Personne n'a besoin de se passer l'appareil.",
      'Orienté vers la personne qui lit',
      "Chaque case pivote par pas de 90° pour que le texte se lise à l'endroit depuis la place de la personne. Faire pivoter une case ne fait jamais pivoter l'écran, et ne renverse jamais les langues qui s'écrivent de droite à gauche.",
      'Appuyer pour parler, ou maintenir',
      "Appuyez une fois pour lancer un tour de parole et laissez-le se terminer seul, ou maintenez le bouton pendant que vous parlez. Les autres micros s'estompent tant que quelqu'un parle, pour que deux voix ne se chevauchent pas.",
      'Ouvrir Discuter',
    ],
    ar: [
      'مترجم محادثة لشخصين إلى أربعة | LingoLive',
      'هاتف واحد على الطاولة وحتى أربع لغات. كل شخص يقرأ بلغته من جهته ويتحدث بزره الخاص.',
      'مترجم محادثة تضعه على الطاولة',
      'ضع الهاتف بينكم. لكل شخص بطاقة موجّهة نحوه: لغته وميكروفونه وجهته من الطاولة. لا حاجة لتمرير الجهاز بينكم.',
      'موجَّه نحو من يقرأ',
      'يمكن تدوير كل بطاقة بخطوات 90° ليُقرأ النص معتدلًا من مكان جلوس صاحبها. تدوير البطاقة لا يدوّر الشاشة أبدًا ولا يقلب اللغات التي تُكتب من اليمين إلى اليسار.',
      'اضغط للتحدث أو استمر بالضغط',
      'اضغط مرة لبدء دورك واترك النظام ينهيه، أو استمر بالضغط أثناء الكلام. تخفت بقية الميكروفونات أثناء حديث أحدهم حتى لا يتداخل صوتان.',
      'افتح وضع التحدّث',
    ],
    es: [
      'Traductor de conversaciones para 2 a 4 personas | LingoLive',
      'Un móvil sobre la mesa y hasta cuatro idiomas. Cada persona lee en su idioma desde su lado y habla con su propio botón.',
      'Un traductor de conversaciones que dejas sobre la mesa',
      'Deja el móvil entre vosotros. Cada persona tiene su panel orientado hacia ella: su idioma, su micrófono, su lado de la mesa. Nadie tiene que pasarse el aparato.',
      'Orientado hacia quien lo lee',
      'Cada panel gira en pasos de 90° para que el texto se lea derecho desde donde está sentada esa persona. Girar un panel nunca gira la pantalla ni voltea al revés los idiomas de derecha a izquierda.',
      'Pulsar para hablar o mantener',
      'Toca una vez para empezar un turno y deja que termine solo, o mantén el botón mientras hablas. Los demás micrófonos se atenúan mientras alguien habla, para que dos voces no se solapen.',
      'Abrir Conversar',
    ],
    'pt-BR': [
      'Tradutor de conversa para 2 a 4 pessoas | LingoLive',
      'Um celular sobre a mesa e até quatro idiomas. Cada pessoa lê no seu idioma do seu lado e fala com o seu próprio botão.',
      'Um tradutor de conversa que você deixa na mesa',
      'Deixe o celular entre vocês. Cada pessoa tem seu painel voltado para si: o idioma dela, o microfone dela, o lado dela da mesa. Ninguém precisa passar o aparelho.',
      'Voltado para quem está lendo',
      'Cada painel gira em passos de 90° para que o texto fique na posição certa de onde a pessoa está sentada. Girar um painel nunca gira a tela nem inverte os idiomas escritos da direita para a esquerda.',
      'Toque para falar, ou segure',
      'Toque uma vez para iniciar sua vez e deixe terminar sozinha, ou segure o botão enquanto fala. Os outros microfones ficam esmaecidos enquanto alguém fala, para que duas vozes não se sobreponham.',
      'Abrir Conversar',
    ],
    it: [
      'Traduttore di conversazione per 2-4 persone | LingoLive',
      'Un telefono sul tavolo, fino a quattro lingue. Ognuno legge nella propria lingua dal proprio lato e parla con il proprio pulsante.',
      'Un traduttore di conversazione da appoggiare sul tavolo',
      'Appoggia il telefono in mezzo a voi. Ognuno ha il proprio riquadro rivolto verso di sé: la sua lingua, il suo microfono, il suo lato del tavolo. Nessuno deve passarsi il dispositivo.',
      'Orientato verso chi legge',
      'Ogni riquadro ruota a passi di 90° perché il testo si legga dritto dal posto di quella persona. Ruotare un riquadro non ruota mai lo schermo e non capovolge le lingue che si scrivono da destra a sinistra.',
      'Premi per parlare, o tieni premuto',
      'Tocca una volta per iniziare il tuo turno e lascia che finisca da solo, oppure tieni premuto mentre parli. Gli altri microfoni si attenuano mentre qualcuno parla, così due voci non si sovrappongono.',
      'Apri Parla',
    ],
    de: [
      'Gesprächsübersetzer für 2 bis 4 Personen | LingoLive',
      'Ein Handy auf dem Tisch, bis zu vier Sprachen. Jede Person liest in ihrer Sprache von ihrer Seite und spricht mit ihrer eigenen Taste.',
      'Ein Gesprächsübersetzer, den du auf den Tisch legst',
      'Leg das Handy zwischen euch. Jede Person bekommt eine ihr zugewandte Kachel: ihre Sprache, ihr Mikrofon, ihre Tischseite. Niemand muss das Gerät herumreichen.',
      'Gedreht für die Person, die liest',
      'Jede Kachel lässt sich in 90°-Schritten drehen, damit der Text von diesem Platz aus aufrecht steht. Eine Kachel zu drehen dreht nie den Bildschirm und kippt nie Rechts-nach-links-Sprachen falsch herum.',
      'Antippen zum Sprechen, oder halten',
      'Einmal tippen, um einen Redebeitrag zu starten und von selbst enden zu lassen — oder die Taste beim Sprechen gedrückt halten. Die anderen Mikrofone werden abgeblendet, solange jemand spricht, damit sich keine zwei Stimmen überlagern.',
      'Sprechen öffnen',
    ],
  },
});

const conferenceCaptions = buildPage({
  path: 'conference-captions',
  kind: 'use-case',
  ctaPath: 'join',
  rows: {
    en: [
      'Conference captions attendees can actually read | LingoLive',
      'Attendees scan a code and read the talk in their own language. One transcription and one translation per language serve the whole room.',
      'Captions for a room full of people',
      'An organizer shows a six-digit code. Attendees scan it or type it, pick a language, and read along on their own phone. No account, no download, nothing to install before the talk starts.',
      'One translation, thousands of readers',
      'The talk is transcribed once and translated once per language people are actually reading. Adding the five-thousandth attendee costs one more connection, not one more translation — which is what makes it viable at conference scale.',
      'Reconnection without holes',
      'Venue Wi-Fi drops. When a phone comes back, it tells the server the last line it displayed and receives exactly what it missed — no duplicates, no gap in the middle of a sentence.',
      'Join a session',
    ],
    fr: [
      'Des sous-titres de conférence vraiment lisibles | LingoLive',
      "Les participants scannent un code et lisent l'intervention dans leur langue. Une transcription et une traduction par langue suffisent à toute la salle.",
      'Des sous-titres pour une salle entière',
      "L'organisateur affiche un code à six chiffres. Les participants le scannent ou le saisissent, choisissent une langue, et lisent sur leur propre téléphone. Sans compte, sans téléchargement, rien à installer avant le début.",
      'Une traduction, des milliers de lecteurs',
      "L'intervention est transcrite une fois et traduite une fois par langue réellement lue. Le cinq millième participant coûte une connexion de plus, pas une traduction de plus — c'est ce qui rend l'échelle d'une conférence tenable.",
      'Une reconnexion sans trous',
      "Le Wi-Fi d'un lieu tombe. Quand un téléphone revient, il indique la dernière ligne affichée et reçoit exactement ce qu'il a manqué — sans doublon et sans trou au milieu d'une phrase.",
      'Rejoindre une session',
    ],
    ar: [
      'نصوص مؤتمرات يمكن للحضور قراءتها فعلًا | LingoLive',
      'يمسح الحضور رمزًا ويقرأون الكلمة بلغتهم. تفريغ واحد وترجمة واحدة لكل لغة تكفي القاعة كلها.',
      'نصوص لقاعة مليئة بالناس',
      'يعرض المنظّم رمزًا من ستة أرقام. يمسحه الحضور أو يكتبونه، يختارون لغة، ويقرأون على هواتفهم. دون حساب ودون تنزيل ودون أي تثبيت قبل البدء.',
      'ترجمة واحدة، آلاف القرّاء',
      'تُفرَّغ الكلمة مرة واحدة وتُترجَم مرة واحدة لكل لغة يقرأها الناس فعلًا. الحاضر رقم خمسة آلاف يكلّف اتصالًا إضافيًا، لا ترجمة إضافية — وهذا ما يجعل حجم المؤتمر ممكنًا.',
      'إعادة اتصال بلا فجوات',
      'شبكة القاعة تنقطع. عندما يعود الهاتف يخبر الخادم بآخر سطر عرضه فيستقبل ما فاته بالضبط — دون تكرار ودون فجوة في منتصف الجملة.',
      'الانضمام إلى جلسة',
    ],
    es: [
      'Subtítulos de congreso que se pueden leer de verdad | LingoLive',
      'El público escanea un código y lee la ponencia en su idioma. Una transcripción y una traducción por idioma bastan para toda la sala.',
      'Subtítulos para una sala llena',
      'La organización muestra un código de seis dígitos. Los asistentes lo escanean o lo escriben, eligen idioma y leen en su propio móvil. Sin cuenta, sin descargas y sin nada que instalar antes de empezar.',
      'Una traducción, miles de lectores',
      'La ponencia se transcribe una vez y se traduce una vez por idioma que la gente realmente lee. El asistente cinco mil cuesta una conexión más, no una traducción más: eso es lo que hace viable la escala de un congreso.',
      'Reconexión sin huecos',
      'El wifi de una sede se cae. Cuando un móvil vuelve, indica la última línea mostrada y recibe exactamente lo que se perdió: sin duplicados y sin un hueco a mitad de frase.',
      'Unirse a una sesión',
    ],
    'pt-BR': [
      'Legendas de congresso que dá para ler de verdade | LingoLive',
      'O público escaneia um código e lê a palestra no seu idioma. Uma transcrição e uma tradução por idioma atendem a sala inteira.',
      'Legendas para uma sala cheia',
      'A organização mostra um código de seis dígitos. As pessoas escaneiam ou digitam, escolhem um idioma e leem no próprio celular. Sem conta, sem download e sem nada para instalar antes de começar.',
      'Uma tradução, milhares de leitores',
      'A palestra é transcrita uma vez e traduzida uma vez por idioma que as pessoas realmente leem. A pessoa de número cinco mil custa mais uma conexão, não mais uma tradução — é isso que torna a escala de um congresso viável.',
      'Reconexão sem buracos',
      'O wi-fi do local cai. Quando o celular volta, ele informa a última linha exibida e recebe exatamente o que perdeu: sem duplicatas e sem buraco no meio de uma frase.',
      'Entrar em uma sessão',
    ],
    it: [
      'Sottotitoli per congressi davvero leggibili | LingoLive',
      'I partecipanti scansionano un codice e leggono l’intervento nella loro lingua. Una trascrizione e una traduzione per lingua bastano per tutta la sala.',
      'Sottotitoli per una sala piena',
      'L’organizzazione mostra un codice a sei cifre. I partecipanti lo scansionano o lo digitano, scelgono una lingua e leggono sul proprio telefono. Senza account, senza download, senza nulla da installare prima dell’inizio.',
      'Una traduzione, migliaia di lettori',
      'L’intervento viene trascritto una volta e tradotto una volta per lingua effettivamente letta. Il cinquemillesimo partecipante costa una connessione in più, non una traduzione in più: è questo a rendere sostenibile la scala di un congresso.',
      'Riconnessione senza buchi',
      'Il Wi-Fi di una sede cade. Quando un telefono torna online comunica l’ultima riga mostrata e riceve esattamente ciò che ha perso: nessun duplicato e nessun buco a metà frase.',
      'Entra in una sessione',
    ],
    de: [
      'Konferenzuntertitel, die man wirklich lesen kann | LingoLive',
      'Teilnehmende scannen einen Code und lesen den Vortrag in ihrer Sprache. Eine Transkription und eine Übersetzung pro Sprache versorgen den ganzen Saal.',
      'Untertitel für einen vollen Saal',
      'Die Veranstaltung zeigt einen sechsstelligen Code. Teilnehmende scannen oder tippen ihn, wählen eine Sprache und lesen auf dem eigenen Handy mit. Ohne Konto, ohne Download, ohne irgendetwas vor dem Start zu installieren.',
      'Eine Übersetzung, tausende Lesende',
      'Der Vortrag wird einmal transkribiert und einmal pro tatsächlich gelesener Sprache übersetzt. Die fünftausendste Person kostet eine Verbindung mehr, nicht eine Übersetzung mehr — genau das macht Konferenzgröße tragfähig.',
      'Wiederverbinden ohne Lücken',
      'Das WLAN einer Location bricht weg. Kommt ein Handy zurück, nennt es die zuletzt angezeigte Zeile und bekommt genau das Fehlende — ohne Dubletten und ohne Lücke mitten im Satz.',
      'Einer Sitzung beitreten',
    ],
  },
});

const meetingTranscription = buildPage({
  path: 'meeting-transcription',
  kind: 'use-case',
  ctaPath: 'listen',
  rows: {
    en: [
      'Meeting transcription without a meeting bot | LingoLive',
      'Read a meeting live from the phone on the table. No bot joining the call, no recording, no calendar integration to set up.',
      'Meeting transcription, without turning your meeting into software',
      'LingoLive is not a meeting platform and does not join your call. It listens through the device in the room, writes the conversation out live, and stops the moment you end the session.',
      'Nothing joins your call',
      'There is no bot in the participant list, no recording notice to explain, and nothing connected to your calendar. It is a phone on the table doing one job.',
      'You decide what is kept',
      'The transcript exists in front of you while the meeting runs. At the end you choose: save it, share the text, or delete it. Nothing is kept by default and audio is never stored at all.',
      'Start listening',
    ],
    fr: [
      'Transcrire une réunion sans robot de réunion | LingoLive',
      "Lisez une réunion en direct depuis le téléphone posé sur la table. Aucun robot dans l'appel, aucun enregistrement, aucune intégration d'agenda à configurer.",
      'Transcrire une réunion sans transformer la réunion en logiciel',
      "LingoLive n'est pas une plateforme de réunion et ne rejoint pas votre appel. Il écoute par l'appareil présent dans la pièce, écrit la conversation en direct, et s'arrête dès que vous terminez la session.",
      'Rien ne rejoint votre appel',
      "Pas de robot dans la liste des participants, pas d'avis d'enregistrement à justifier, rien de connecté à votre agenda. Juste un téléphone sur la table qui fait une seule chose.",
      'Vous décidez de ce qui est conservé',
      "Le transcript est devant vous pendant la réunion. À la fin, vous choisissez : le sauvegarder, partager le texte, ou le supprimer. Rien n'est conservé par défaut, et l'audio n'est jamais stocké.",
      'Commencer à écouter',
    ],
    ar: [
      'تفريغ الاجتماعات دون روبوت اجتماعات | LingoLive',
      'اقرأ الاجتماع مباشرةً من الهاتف الموضوع على الطاولة. لا روبوت ينضم إلى المكالمة، ولا تسجيل، ولا تكامل مع التقويم.',
      'تفريغ الاجتماع دون تحويل الاجتماع إلى برنامج',
      'LingoLive ليس منصة اجتماعات ولا ينضم إلى مكالمتك. يستمع عبر الجهاز الموجود في الغرفة، ويكتب الحوار مباشرةً، ويتوقف فور إنهائك للجلسة.',
      'لا شيء ينضم إلى مكالمتك',
      'لا روبوت في قائمة المشاركين، ولا إشعار تسجيل تشرحه، ولا شيء متصل بتقويمك. مجرد هاتف على الطاولة يؤدي مهمة واحدة.',
      'أنت من يقرر ما يُحفظ',
      'يكون النص أمامك أثناء الاجتماع. وفي النهاية تختار: احفظه أو شارك النص أو احذفه. لا يُحفظ شيء افتراضيًا، والصوت لا يُخزَّن إطلاقًا.',
      'ابدأ الاستماع',
    ],
    es: [
      'Transcribir una reunión sin bots de reunión | LingoLive',
      'Lee una reunión en directo desde el móvil que está sobre la mesa. Sin bots en la llamada, sin grabación y sin integraciones de calendario que configurar.',
      'Transcribir una reunión sin convertir la reunión en software',
      'LingoLive no es una plataforma de reuniones y no se une a tu llamada. Escucha con el dispositivo que hay en la sala, escribe la conversación en directo y se detiene en cuanto terminas la sesión.',
      'Nada se une a tu llamada',
      'No hay un bot en la lista de participantes, ni un aviso de grabación que justificar, ni nada conectado a tu calendario. Es un móvil sobre la mesa haciendo una sola cosa.',
      'Tú decides qué se conserva',
      'La transcripción está delante de ti mientras dura la reunión. Al final eliges: guardarla, compartir el texto o borrarla. No se conserva nada por defecto y el audio nunca se almacena.',
      'Empezar a escuchar',
    ],
    'pt-BR': [
      'Transcrever uma reunião sem bot de reunião | LingoLive',
      'Leia a reunião ao vivo pelo celular que está sobre a mesa. Sem bot entrando na chamada, sem gravação e sem integração de calendário para configurar.',
      'Transcrever a reunião sem transformar a reunião em software',
      'O LingoLive não é uma plataforma de reuniões e não entra na sua chamada. Ele ouve pelo aparelho que está na sala, escreve a conversa ao vivo e para no instante em que você encerra a sessão.',
      'Nada entra na sua chamada',
      'Não há bot na lista de participantes, nem aviso de gravação para explicar, nem nada ligado ao seu calendário. É um celular na mesa fazendo uma coisa só.',
      'Você decide o que fica',
      'A transcrição fica diante de você durante a reunião. No fim, você escolhe: salvar, compartilhar o texto ou excluir. Nada é guardado por padrão e o áudio nunca é armazenado.',
      'Começar a ouvir',
    ],
    it: [
      'Trascrivere una riunione senza bot di riunione | LingoLive',
      'Leggi la riunione in diretta dal telefono appoggiato sul tavolo. Nessun bot che entra nella chiamata, nessuna registrazione, nessuna integrazione di calendario da configurare.',
      'Trascrivere la riunione senza trasformarla in software',
      'LingoLive non è una piattaforma di riunioni e non entra nella tua chiamata. Ascolta dal dispositivo presente nella stanza, scrive la conversazione in diretta e si ferma nell’istante in cui chiudi la sessione.',
      'Niente entra nella tua chiamata',
      'Nessun bot nella lista partecipanti, nessun avviso di registrazione da spiegare, niente collegato al tuo calendario. È un telefono sul tavolo che fa una cosa sola.',
      'Decidi tu cosa resta',
      'La trascrizione è davanti a te mentre la riunione va avanti. Alla fine scegli: salvarla, condividere il testo o cancellarla. Per impostazione predefinita non resta nulla, e l’audio non viene mai conservato.',
      'Inizia ad ascoltare',
    ],
    de: [
      'Meeting-Transkription ohne Meeting-Bot | LingoLive',
      'Lies ein Meeting live vom Handy auf dem Tisch. Kein Bot im Call, keine Aufzeichnung, keine Kalender-Integration einzurichten.',
      'Meeting-Transkription, ohne dein Meeting in Software zu verwandeln',
      'LingoLive ist keine Meeting-Plattform und tritt deinem Call nicht bei. Es hört über das Gerät im Raum mit, schreibt das Gespräch live mit und hört auf, sobald du die Sitzung beendest.',
      'Nichts tritt deinem Call bei',
      'Kein Bot in der Teilnehmerliste, kein Aufzeichnungshinweis zu erklären, nichts mit deinem Kalender verbunden. Ein Handy auf dem Tisch, das genau eine Aufgabe hat.',
      'Du entscheidest, was bleibt',
      'Das Transkript liegt während des Meetings vor dir. Am Ende entscheidest du: speichern, den Text teilen oder löschen. Standardmäßig bleibt nichts, und Audio wird überhaupt nie gespeichert.',
      'Jetzt zuhören',
    ],
  },
});

const travelTranslation = buildPage({
  path: 'travel-translation',
  kind: 'use-case',
  ctaPath: 'discuss',
  rows: {
    en: [
      'Travel translator for real conversations | LingoLive',
      'Ask a question at a station, a pharmacy or a market and read the answer. Hand-free, on one phone, without passing it back and forth.',
      'A travel translator for the conversation, not just the phrase',
      'Travel translation usually means typing a sentence and showing a screen. LingoLive lets both people just talk: one phone between you, each side reading in their own language.',
      'Works when you are standing up',
      'Very large text, high contrast, and a microphone button big enough to hit without looking. The screen stays awake while the conversation lasts.',
      'Needs a connection — and says so',
      'Live transcription requires the internet. LingoLive tells you plainly when you are offline rather than silently failing, so you are never left staring at a screen that is not listening.',
      'Open Discuss',
    ],
    fr: [
      'Traducteur de voyage pour de vraies conversations | LingoLive',
      'Posez une question à une gare, une pharmacie ou un marché, et lisez la réponse. Sans se passer le téléphone, sur un seul appareil.',
      'Un traducteur de voyage pour la conversation, pas seulement pour la phrase',
      'La traduction de voyage se résume souvent à taper une phrase et montrer un écran. Avec LingoLive, les deux personnes parlent simplement : un téléphone entre vous, chacun lit dans sa langue.',
      'Utilisable debout',
      "Texte très grand, contraste élevé, et un bouton micro assez grand pour être touché sans regarder. L'écran reste allumé tant que la conversation dure.",
      'Nécessite une connexion — et le dit',
      "La transcription en direct a besoin d'Internet. LingoLive vous le dit clairement quand vous êtes hors ligne plutôt que d'échouer en silence, pour que vous ne restiez jamais devant un écran qui n'écoute pas.",
      'Ouvrir Discuter',
    ],
    ar: [
      'مترجم سفر لمحادثات حقيقية | LingoLive',
      'اسأل في محطة أو صيدلية أو سوق واقرأ الجواب. دون تمرير الهاتف، وعلى جهاز واحد.',
      'مترجم سفر للمحادثة، لا للجملة وحدها',
      'ترجمة السفر عادةً تعني كتابة جملة وعرض الشاشة. مع LingoLive يتحدث الطرفان ببساطة: هاتف واحد بينكما، وكل جهة تقرأ بلغتها.',
      'يعمل وأنت واقف',
      'نص كبير جدًا وتباين عالٍ وزر ميكروفون كبير يكفي للضغط عليه دون النظر. تبقى الشاشة مضاءة ما دامت المحادثة قائمة.',
      'يحتاج اتصالًا — ويقول ذلك',
      'يحتاج التفريغ المباشر إلى الإنترنت. يخبرك LingoLive بوضوح عندما تكون غير متصل بدل أن يفشل بصمت، فلا تبقى أمام شاشة لا تستمع.',
      'افتح وضع التحدّث',
    ],
    es: [
      'Traductor de viaje para conversaciones reales | LingoLive',
      'Pregunta en una estación, una farmacia o un mercado y lee la respuesta. Sin pasarse el móvil, en un solo aparato.',
      'Un traductor de viaje para la conversación, no solo para la frase',
      'La traducción de viaje suele consistir en teclear una frase y enseñar la pantalla. Con LingoLive las dos personas simplemente hablan: un móvil entre vosotros y cada lado leyendo en su idioma.',
      'Funciona de pie',
      'Texto muy grande, alto contraste y un botón de micrófono lo bastante grande para acertar sin mirar. La pantalla no se apaga mientras dura la conversación.',
      'Necesita conexión, y lo dice',
      'La transcripción en directo necesita internet. LingoLive te lo dice con claridad cuando estás sin conexión en lugar de fallar en silencio, para que nunca te quedes mirando una pantalla que no escucha.',
      'Abrir Conversar',
    ],
    'pt-BR': [
      'Tradutor de viagem para conversas de verdade | LingoLive',
      'Pergunte numa estação, numa farmácia ou num mercado e leia a resposta. Sem passar o celular, num aparelho só.',
      'Um tradutor de viagem para a conversa, não só para a frase',
      'Tradução de viagem costuma significar digitar uma frase e mostrar a tela. Com o LingoLive as duas pessoas simplesmente falam: um celular entre vocês, cada lado lendo no seu idioma.',
      'Funciona em pé',
      'Texto bem grande, alto contraste e um botão de microfone grande o bastante para acertar sem olhar. A tela fica acesa enquanto a conversa durar.',
      'Precisa de conexão — e avisa',
      'A transcrição ao vivo precisa de internet. O LingoLive avisa claramente quando você está offline em vez de falhar em silêncio, para você nunca ficar olhando uma tela que não está ouvindo.',
      'Abrir Conversar',
    ],
    it: [
      'Traduttore da viaggio per conversazioni vere | LingoLive',
      'Fai una domanda in stazione, in farmacia o al mercato e leggi la risposta. Senza passarsi il telefono, su un solo dispositivo.',
      'Un traduttore da viaggio per la conversazione, non solo per la frase',
      'La traduzione da viaggio di solito significa digitare una frase e mostrare lo schermo. Con LingoLive le due persone parlano e basta: un telefono in mezzo a voi, ciascun lato che legge nella propria lingua.',
      'Funziona anche in piedi',
      'Testo molto grande, contrasto elevato e un pulsante microfono abbastanza grande da centrare senza guardare. Lo schermo resta acceso finché dura la conversazione.',
      'Serve una connessione — e lo dice',
      'La trascrizione in diretta richiede Internet. LingoLive te lo dice chiaramente quando sei offline invece di fallire in silenzio, così non resti mai davanti a uno schermo che non ascolta.',
      'Apri Parla',
    ],
    de: [
      'Reise-Übersetzer für echte Gespräche | LingoLive',
      'Stell eine Frage am Bahnhof, in der Apotheke oder auf dem Markt und lies die Antwort. Ohne das Handy hin und her zu reichen, auf einem Gerät.',
      'Ein Reise-Übersetzer für das Gespräch, nicht nur für den Satz',
      'Reise-Übersetzung heißt meist: Satz tippen, Bildschirm zeigen. Mit LingoLive reden beide einfach: ein Handy zwischen euch, jede Seite liest in ihrer Sprache.',
      'Funktioniert im Stehen',
      'Sehr große Schrift, hoher Kontrast und eine Mikrofontaste, die groß genug ist, um sie ohne Hinsehen zu treffen. Der Bildschirm bleibt an, solange das Gespräch dauert.',
      'Braucht eine Verbindung — und sagt das',
      'Live-Transkription braucht Internet. LingoLive sagt dir klar, wenn du offline bist, statt still zu scheitern — damit du nie auf einen Bildschirm starrst, der nicht zuhört.',
      'Sprechen öffnen',
    ],
  },
});

const accessibilityCaptions = buildPage({
  path: 'accessibility/live-captions',
  kind: 'use-case',
  ctaPath: 'listen',
  rows: {
    en: [
      'Live captions for accessibility | LingoLive',
      'Very large text, high contrast, screen-reader support and a screen that stays awake. Built so a deaf or hard-of-hearing person can follow a room.',
      'Live captions built for accessibility, not retrofitted',
      'Accessibility is the reason several of LingoLive’s core decisions exist: the transcript scales far beyond a normal font size, it meets contrast requirements in both themes, and it never relies on colour alone to tell you anything.',
      'Screen readers that stay usable',
      'Announcing every partial word would make a screen reader unusable during a live transcript. LingoLive announces completed lines only, at a readable pace, and marks the transcript as a live region so nothing is lost.',
      'Designed to WCAG 2.2 AA',
      'Contrast ratios are asserted in the test suite, every control is at least 48×48, focus is always visible, the whole product is reachable by keyboard, and animations collapse to nothing when Reduce Motion is on.',
      'Start listening',
    ],
    fr: [
      "Sous-titres en direct pour l'accessibilité | LingoLive",
      "Texte très grand, contraste élevé, lecteurs d'écran et écran qui reste allumé. Conçu pour qu'une personne sourde ou malentendante puisse suivre une salle.",
      "Des sous-titres en direct conçus pour l'accessibilité, pas ajoutés après coup",
      "L'accessibilité explique plusieurs choix fondamentaux de LingoLive : le transcript s'agrandit bien au-delà d'une taille de texte normale, il respecte les exigences de contraste dans les deux thèmes, et il ne s'appuie jamais sur la couleur seule pour transmettre une information.",
      "Des lecteurs d'écran qui restent utilisables",
      "Annoncer chaque mot partiel rendrait un lecteur d'écran inutilisable pendant une transcription en direct. LingoLive n'annonce que les lignes terminées, à un rythme lisible, et déclare le transcript comme zone live pour que rien ne se perde.",
      'Conçu selon WCAG 2.2 AA',
      'Les ratios de contraste sont vérifiés par les tests, chaque commande fait au moins 48×48, le focus est toujours visible, tout le produit est accessible au clavier, et les animations tombent à zéro quand « Réduire les animations » est actif.',
      'Commencer à écouter',
    ],
    ar: [
      'نصوص مباشرة من أجل إمكانية الوصول | LingoLive',
      'نص كبير جدًا وتباين عالٍ ودعم لقارئات الشاشة وشاشة تبقى مضاءة. مصمَّم ليتمكن الأصمّ أو ضعيف السمع من متابعة القاعة.',
      'نصوص مباشرة مصمَّمة لإمكانية الوصول، لا مُضافة لاحقًا',
      'إمكانية الوصول هي سبب عدة قرارات جوهرية في LingoLive: يتوسّع النص إلى ما هو أبعد بكثير من الحجم المعتاد، ويستوفي متطلبات التباين في الوضعين، ولا يعتمد أبدًا على اللون وحده لنقل معلومة.',
      'قارئات شاشة تبقى قابلة للاستخدام',
      'إعلان كل كلمة مؤقتة يجعل قارئ الشاشة غير قابل للاستعمال أثناء التفريغ المباشر. يعلن LingoLive الأسطر المكتملة فقط بوتيرة مقروءة، ويعرّف النص كمنطقة حيّة حتى لا يضيع شيء.',
      'مصمَّم وفق WCAG 2.2 AA',
      'نسب التباين مُختبَرة آليًا، وكل عنصر تفاعلي لا يقل عن 48×48، والتركيز مرئي دائمًا، والمنتج كله يعمل بلوحة المفاتيح، وتتوقف الحركات تمامًا عند تفعيل «تقليل الحركة».',
      'ابدأ الاستماع',
    ],
    es: [
      'Subtítulos en directo para accesibilidad | LingoLive',
      'Texto muy grande, alto contraste, compatibilidad con lectores de pantalla y una pantalla que no se apaga. Pensado para que una persona sorda o con hipoacusia pueda seguir una sala.',
      'Subtítulos en directo diseñados para la accesibilidad, no añadidos después',
      'La accesibilidad explica varias decisiones centrales de LingoLive: la transcripción se amplía mucho más allá de un tamaño de texto normal, cumple los requisitos de contraste en ambos temas y nunca depende solo del color para comunicar algo.',
      'Lectores de pantalla que siguen siendo usables',
      'Anunciar cada palabra parcial haría inservible un lector de pantalla durante una transcripción en directo. LingoLive anuncia solo las líneas terminadas, a un ritmo legible, y declara la transcripción como región activa para que nada se pierda.',
      'Diseñado según WCAG 2.2 AA',
      'Las relaciones de contraste están verificadas en los tests, cada control mide al menos 48×48, el foco siempre es visible, todo el producto se maneja con teclado y las animaciones se anulan cuando está activo «Reducir movimiento».',
      'Empezar a escuchar',
    ],
    'pt-BR': [
      'Legendas ao vivo para acessibilidade | LingoLive',
      'Texto bem grande, alto contraste, suporte a leitores de tela e uma tela que fica acesa. Feito para que uma pessoa surda ou com perda auditiva consiga acompanhar uma sala.',
      'Legendas ao vivo pensadas para acessibilidade, não adaptadas depois',
      'A acessibilidade é a razão de várias decisões centrais do LingoLive: a transcrição amplia muito além de um tamanho de texto comum, atende aos requisitos de contraste nos dois temas e nunca usa só a cor para comunicar algo.',
      'Leitores de tela que continuam usáveis',
      'Anunciar cada palavra parcial tornaria um leitor de tela inutilizável durante uma transcrição ao vivo. O LingoLive anuncia apenas as linhas concluídas, num ritmo legível, e marca a transcrição como região ativa para que nada se perca.',
      'Projetado segundo a WCAG 2.2 AA',
      'As razões de contraste são verificadas nos testes, cada controle tem no mínimo 48×48, o foco é sempre visível, todo o produto funciona por teclado e as animações vão a zero quando “Reduzir movimento” está ativo.',
      'Começar a ouvir',
    ],
    it: [
      'Sottotitoli in diretta per l’accessibilità | LingoLive',
      'Testo molto grande, contrasto elevato, supporto agli screen reader e uno schermo che resta acceso. Pensato perché una persona sorda o ipoacusica possa seguire una sala.',
      'Sottotitoli in diretta progettati per l’accessibilità, non aggiunti dopo',
      'L’accessibilità è la ragione di diverse scelte centrali di LingoLive: la trascrizione si ingrandisce ben oltre una dimensione di testo normale, rispetta i requisiti di contrasto in entrambi i temi e non affida mai al solo colore un’informazione.',
      'Screen reader che restano usabili',
      'Annunciare ogni parola provvisoria renderebbe uno screen reader inutilizzabile durante una trascrizione in diretta. LingoLive annuncia solo le righe completate, a un ritmo leggibile, e dichiara la trascrizione come regione live perché nulla vada perso.',
      'Progettato secondo WCAG 2.2 AA',
      'I rapporti di contrasto sono verificati dai test, ogni controllo misura almeno 48×48, il focus è sempre visibile, tutto il prodotto è raggiungibile da tastiera e le animazioni si azzerano quando «Riduci movimento» è attivo.',
      'Inizia ad ascoltare',
    ],
    de: [
      'Live-Untertitel für Barrierefreiheit | LingoLive',
      'Sehr große Schrift, hoher Kontrast, Screenreader-Unterstützung und ein Bildschirm, der anbleibt. Gebaut, damit gehörlose und schwerhörige Menschen einem Raum folgen können.',
      'Live-Untertitel, für Barrierefreiheit entworfen statt nachgerüstet',
      'Barrierefreiheit ist der Grund für mehrere zentrale Entscheidungen in LingoLive: Das Transkript skaliert weit über eine normale Schriftgröße hinaus, erfüllt die Kontrastanforderungen in beiden Themes und verlässt sich nie allein auf Farbe, um etwas mitzuteilen.',
      'Screenreader, die nutzbar bleiben',
      'Jedes vorläufige Wort anzusagen machte einen Screenreader während eines Live-Transkripts unbrauchbar. LingoLive sagt nur fertige Zeilen an, in lesbarem Tempo, und markiert das Transkript als Live-Region, damit nichts verloren geht.',
      'Nach WCAG 2.2 AA gebaut',
      'Kontrastverhältnisse werden im Test geprüft, jedes Bedienelement misst mindestens 48×48, der Fokus ist immer sichtbar, das ganze Produkt ist per Tastatur erreichbar, und Animationen fallen auf null, wenn „Bewegung reduzieren“ aktiv ist.',
      'Jetzt zuhören',
    ],
  },
});

export const USE_CASE_PAGES: readonly MarketingPage[] = [
  conversationTranslator,
  conferenceCaptions,
  meetingTranscription,
  travelTranslation,
  accessibilityCaptions,
];
